import { Sequelize } from "sequelize-typescript";
import dotenv from 'dotenv';
dotenv.config();
const dbName: string | undefined  = String(process.env.DB_NAME);
const dbHost  =  process.env.DB_HOST;
const dbUsername : string | undefined =  String(process.env.DB_USERNAME);
const dbPassword =  process.env.DB_PASSWORD;
const dialect = "mysql";
const seqlzConnexion =  new Sequelize(dbName,dbUsername,dbPassword,{host:dbHost, dialect:dialect});
export default  seqlzConnexion;